title: blog ...
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skandyn-sh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

plugins:
- jekyll-paginate

paginate: 2 
paginate_path: page:num
