title: My simple blog
email: mzarze@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skandyn-sh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima

collections:
  photos:
    output: true

defaults:
  - scope:
      path: "_photos"
        type: photos
    values:
      layout: photo
