title: My simple blog
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skandyn-sh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

--- 
collections: 
  photos: 
    output: true
defaults: 
  - 
    scope: 
      path: 
        type: photos
    values: 
      layout: photo
